import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[font]
size = 14.0

[font.normal]
family = "MesloLGS NF"

[scrolling]
history = 10000

[window]
decorations = "none"
opacity = 0.9
startup_mode = "SimpleFullscreen"
