import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[font]
normal.family = "MesloLGS NF"
bold.family = "MesloLGS NF"
italic.family = "MesloLGS NF"
bold_italic.family = "MesloLGS NF"

size = 14.0

[scrolling]
history = 10000

[window]
decorations = "none"
opacity = 0.9
startup_mode = "SimpleFullscreen"
